CREATE DATABASE SweebDataBase;

USE SweebDataBase;

CREATE TABLE User_Info (
	IdUser INT PRIMARY KEY IDENTITY(1,1),
	Username NVARCHAR(255) NOT NULL UNIQUE,
	Email NVARCHAR(255) NOT NULL UNIQUE,
	PasswordHash NVARCHAR(255) NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	LastLogin DATETIME,
	PhoneNumber NVARCHAR(20),
);

CREATE TABLE UserSettings (
	IdSettings INT PRIMARY KEY IDENTITY(1,1),
	UserId INT NOT NULL,
	AllwaysOnTop BIT NOT NULL DEFAULT 0,
	AllowNotifications BIT NOT NULL DEFAULT 1,
	Theme NVARCHAR(50) NOT NULL DEFAULT 'Light',
	RunAtStartup BIT NOT NULL DEFAULT 0,
	constraint FK_UserSettings_UserId FOREIGN KEY (UserId) REFERENCES User_Info(IdUser)
);

CREATE TABLE Devices (
	IdDevice INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(255) NOT NULL,
	OS NVARCHAR(255) NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UserId INT NOT NULL,
	CONSTRAINT FK_UserId FOREIGN KEY (UserId) REFERENCES User_Info(IdUser)
);

CREATE TABLE Rules (
	IdRule INT PRIMARY KEY IDENTITY(1,1),
	UserId INT NOT NULL,
	Name NVARCHAR(255) NOT NULL,
	IsEnabled BIT NOT NULL DEFAULT 1,
	Priority INT NOT NULL DEFAULT 0,
	Action NVARCHAR(255) NOT NULL,
	MatchType NVARCHAR(50) NOT NULL,
	Pattern NVARCHAR(255) NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_Rules_UserId FOREIGN KEY (UserId) REFERENCES User_Info(IdUser)
);

CREATE TABLE RuleHits (
	IdRuleHit INT PRIMARY KEY IDENTITY(1,1),
	RuleId INT NOT NULL,
	ThreatEventId INT NOT NULL,
	Timestamp DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_RuleHits_RuleId FOREIGN KEY (RuleId) REFERENCES Rules(IdRule),
	CONSTRAINT FK_RuleHits_ThreatEventId FOREIGN KEY (ThreatEventId) REFERENCES ThreatEvents(IdThreatEvent)
);

CREATE TABLE ThreatEvents (
	IdThreatEvent INT PRIMARY KEY IDENTITY(1,1),
	URL NVARCHAR(2048) NOT NULL,
	Protocol NVARCHAR(10) NOT NULL,
	Host NVARCHAR(255) NOT NULL,
	Path NVARCHAR(2048) NOT NULL,
	Status NVARCHAR(50) NOT NULL,
	Timestamp DATETIME NOT NULL DEFAULT GETDATE(),
	Verdict NVARCHAR(50) NOT NULL,
	ActionTaken NVARCHAR(255) NOT NULL,
	Score INT NOT NULL,
	Category NVARCHAR(255) NOT NULL,
	DeviceID INT NOT NULL,
	CONSTRAINT FK_DeviceID FOREIGN KEY (DeviceID) REFERENCES Devices(IdDevice)
);

CREATE TABLE DetectionReasons (
	IdDetReason INT PRIMARY KEY IDENTITY(1,1),
	ReasonCode NVARCHAR(50) NOT NULL,
	Weight INT NOT NULL,
	Details NVARCHAR(255) NOT NULL,
	ThreatEventId INT NOT NULL,
	CONSTRAINT FK_DetectionReasons_ThreatEventId FOREIGN KEY (ThreatEventId) REFERENCES ThreatEvents(IdThreatEvent)
);

CREATE TABLE Alerts (
	IdAlert INT PRIMARY KEY IDENTITY(1,1),
	UserId INT NOT NULL,
	DeviceId INT NOT NULL,
	ThreatEventId INT NOT NULL,
	Severity NVARCHAR(50) NOT NULL,
	IsRead BIT NOT NULL DEFAULT 0,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_Alerts_UserId FOREIGN KEY (UserId) REFERENCES User_Info(IdUser),
	CONSTRAINT FK_Alerts_DeviceId FOREIGN KEY (DeviceId) REFERENCES Devices(IdDevice),
	CONSTRAINT FK_Alerts_ThreatEventId FOREIGN KEY (ThreatEventId) REFERENCES ThreatEvents(IdThreatEvent)
);
