services:
  sqlserver:
    image: ${IMAGE_NAME}
    container_name : ${DB_NAME}
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${PORT}
    volumes:
    - sql_data:/var/opt/mssql
volumes:
  sql_data:
# Initialize the container with the database : docker compose up -d