CREATE DATABASE SweebDataBase;

USE SweebDataBase;

CREATE TABLE User_Info (
	IdUser INT PRIMARY KEY IDENTITY(1,1),
	Username NVARCHAR(255) NOT NULL UNIQUE
); 

CREATE TABLE Devices (
	IdDevice INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(255) NOT NULL,
	OS NVARCHAR(255) NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	UserId INT NOT NULL,
	CONSTRAINT FK_UserId FOREIGN KEY (UserId) REFERENCES User_Info(IdUser)
);

CREATE TABLE ThreatEvents (
	IdThreatEvent INT PRIMARY KEY IDENTITY(1,1),
	URL NVARCHAR(2048) NOT NULL,
	Protocol NVARCHAR(10) NOT NULL,
	Timestamp DATETIME NOT NULL DEFAULT GETDATE(),
	Verdict NVARCHAR(50) NOT NULL,
	ActionTaken NVARCHAR(255) NOT NULL,
	Score INT NOT NULL,
	Category NVARCHAR(255) NOT NULL,
	DeviceID INT NOT NULL,
	CONSTRAINT FK_DeviceID FOREIGN KEY (DeviceID) REFERENCES Devices(IdDevice)
);


CREATE TABLE Alerts (
	IdAlert INT PRIMARY KEY IDENTITY(1,1),
	UserId INT NOT NULL,
	DeviceId INT NOT NULL,
	ThreatEventId INT NOT NULL,
	Severity NVARCHAR(50) NOT NULL,
	IsRead BIT NOT NULL DEFAULT 0,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_Alerts_UserId FOREIGN KEY (UserId) REFERENCES User_Info(IdUser),
	CONSTRAINT FK_Alerts_DeviceId FOREIGN KEY (DeviceId) REFERENCES Devices(IdDevice),
	CONSTRAINT FK_Alerts_ThreatEventId FOREIGN KEY (ThreatEventId) REFERENCES ThreatEvents(IdThreatEvent)
);

